# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16kH5m07SVQzjscs1LAdmw3Bvpg55wpfN
"""

# Минимальный вариант с базовыми компонентами
from diagrams import Diagram, Cluster, Edge
from diagrams.aws.compute import EC2
from diagrams.aws.database import RDS
from diagrams.aws.storage import S3
from diagrams.aws.general import Users
from diagrams.generic.device import Mobile, Tablet
from diagrams.generic.compute import Rack
from diagrams.generic.storage import Storage
from diagrams.onprem.compute import Server
from diagrams.onprem.network import Nginx
import os

with Diagram("Edge-Fog-Cloud Deployment (Simplified)",
             show=False,
             filename="output/simple_deployment",
             direction="LR"):

    # Edge Level (6 devices)
    with Cluster("EDGE LEVEL (6 devices)"):
        edge1 = Mobile("Sensor 1")
        edge2 = Mobile("Sensor 2")
        edge3 = Tablet("Camera")
        edge4 = Mobile("Sensor 3")
        edge5 = Mobile("Sensor 4")
        edge6 = Tablet("Controller")

    # Fog Level (3 nodes)
    with Cluster("FOG LEVEL (3 nodes)"):
        fog1 = Server("Fog Node 1")
        fog2 = Server("Fog Node 2")
        fog3 = Server("Fog Node 3")

    # Cloud Level (2 servers)
    with Cluster("CLOUD LEVEL (2 servers)"):
        cloud1 = EC2("Cloud Server 1")
        cloud2 = EC2("Cloud Server 2")
        cloud_db = RDS("Database")
        cloud_storage = S3("Storage")

        cloud1 >> cloud_db
        cloud1 >> cloud_storage
        cloud2 >> cloud_storage

    # Users
    users = Users("Users")

    # Connections
    # Edge -> Fog
    edge1 >> fog1
    edge2 >> fog1
    edge3 >> fog1
    edge4 >> fog2
    edge5 >> fog3
    edge6 >> fog3

    # Fog -> Cloud
    fog1 >> cloud1
    fog2 >> cloud1
    fog3 >> cloud2

    # Cloud -> Users
    cloud1 >> users
    cloud2 >> users

print("✅ Упрощенная диаграмма создана!")