# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yBVPxTFbFvPcqTs28N8_pHth4O_YyuXW
"""

!pip install diagrams

from diagrams import Diagram
from diagrams.aws.compute import EC2
from diagrams.aws.network import InternetGateway
from diagrams.onprem.client import User  # Замена для mobile.Client
from diagrams.onprem.compute import Server
from diagrams.aws.iot import IotSensor  # Более подходящий компонент для датчика
from diagrams.generic.device import Mobile  # Альтернатива для смартфона
from diagrams.onprem.network import Internet  # Для лучшего представления

# Укажите путь для сохранения картинки. В Colab это будет текущая директория.
with Diagram("Архитектура IoT системы 'Умный дом'", show=False, filename="iot_architecture"):
    # Определяем ноды (компоненты) системы с более подходящими иконками
    sensor1 = IotSensor("Робот-датчик 1")
    sensor2 = IotSensor("Робот-Датчик 2")
    fog1 = EC2("Fog-обработчик 1")
    fog2 = EC2("Fog-обработчик 2")
    courier = InternetGateway("Робот-курьер")
    smartphone = User("Смартфон\n(Буфер)")
    server = Server("Ноутбук-сервер")
    internet = Internet("Интернет")

    # Строим конвейер обработки данных
    sensor1 >> fog1
    sensor2 >> fog2

    fog1 >> courier
    fog2 >> courier

    courier >> internet
    internet >> smartphone
    smartphone >> server

print("Схема сохранена как 'iot_architecture.png'")
print("Файл будет доступен в левой панели управления файлами Colab")

