# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/112f1rkUB8q9a2pkHSQ1Tao_cDEmQ-I0T
"""

# Установка библиотеки diagrams в Google Colab
!pip install diagrams

from diagrams import Diagram, Cluster, Edge
from diagrams.onprem.client import User
from diagrams.generic.compute import Rack
from diagrams.generic.device import Mobile
from diagrams.onprem.compute import Server
from diagrams.generic.storage import Storage
from diagrams.generic.network import Firewall
from diagrams.onprem.network import Internet

# Определение кастомных узлов для состояний Fog-узла
from diagrams import Node

class StateNode(Node):
    _provider = "custom"
    _icon_dir = None
    font_size = "16"

    def __init__(self, label, **kwargs):
        super().__init__(label, **kwargs)

# Создаем State-диаграмму для Fog-узла
with Diagram("State-диаграмма Fog-узла в архитектуре 'Край-Туман-Облако'",
             show=False,
             direction="LR",
             graph_attr={"splines": "ortho", "ranksep": "2", "nodesep": "2"}):

    # Определяем состояния Fog-узла
    standby = StateNode("Режим ожидания\n(Fog-узел готов к работе)")
    receiving = StateNode("Получение задачи\n(Запрос от краевого устройства)")
    processing = StateNode("Обработка данных\n(Выполнение вычислений)")
    sending = StateNode("Передача результата\n(Отправка на край или в облако)")
    overload = StateNode("Перегрузка/Ожидание\n(Очередь или передача в облако)")
    recovery = StateNode("Восстановление\n(Возврат в нормальный режим)")

    # Создаем связи между состояниями
    standby >> Edge(color="green", label="Поступление запроса") >> receiving
    receiving >> Edge(color="blue", label="Начало обработки") >> processing
    processing >> Edge(color="orange", label="Завершение обработки") >> sending
    sending >> Edge(color="green", label="Успешная отправка") >> standby

    # Альтернативные переходы
    processing >> Edge(color="red", style="dashed", label="Перегрузка CPU/RAM") >> overload
    receiving >> Edge(color="red", style="dashed", label="Слишком много запросов") >> overload
    overload >> Edge(color="blue", label="Передача в облако") >> sending
    overload >> Edge(color="green", label="Восстановление") >> recovery
    recovery >> Edge(color="green", label="Готов к работе") >> standby

    # Добавляем обратные связи
    sending >> Edge(color="red", style="dotted", label="Ошибка отправки") >> overload
    overload >> Edge(color="red", style="dotted", label="Критическая перегрузка") >> overload  # self-loop

# Теперь создадим общую архитектуру системы
with Diagram("Трехуровневая архитектура 'Край-Туман-Облако'\n(5 краевых устройств, 3 Fog-узла, 2 облачных сервера)",
             show=False,
             direction="TB"):

    # Облачный уровень
    cloud_label = "Облачный уровень\n(2 сервера)"
    with Cluster(cloud_label):
        cloud1 = Server("Облачный сервер 1")
        cloud2 = Server("Облачный сервер 2")
        cloud_storage = Storage("Центральное хранилище")

        cloud_group = [cloud1, cloud2, cloud_storage]
        cloud1 - cloud2
        cloud1 >> cloud_storage
        cloud2 >> cloud_storage

    # Fog-уровень
    fog_label = "Fog-уровень\n(3 узла)"
    with Cluster(fog_label):
        fog1 = Server("Fog-узел 1")
        fog2 = Server("Fog-узел 2")
        fog3 = Server("Fog-узел 3")

        fog_group = [fog1, fog2, fog3]
        fog1 - fog2 - fog3

    # Краевой уровень
    edge_label = "Краевой уровень\n(5 устройств)"
    with Cluster(edge_label):
        edge1 = Mobile("Краевое устройство 1")
        edge2 = Mobile("Краевое устройство 2")
        edge3 = Mobile("Краевое устройство 3")
        edge4 = Mobile("Краевое устройство 4")
        edge5 = Mobile("Краевое устройство 5")

        edge_group = [edge1, edge2, edge3, edge4, edge5]

    # Соединения между уровнями
    internet = Internet("Сеть")

    # Край -> Fog
    for edge in edge_group:
        edge >> Edge(color="blue", label="Данные с датчиков") >> internet

    internet >> Edge(color="blue", label="Распределение нагрузки") >> fog_group

    # Fog -> Облако
    for fog in fog_group:
        fog >> Edge(color="orange", label="Агрегированные данные", style="dashed") >> cloud_group

    # Облако -> Fog (управление и обновления)
    cloud1 >> Edge(color="green", label="Управление/обновления", style="dotted") >> fog_group

    # Прямые соединения Край-Облако (для экстренных случаев)
    edge1 >> Edge(color="red", label="Экстренные данные", style="dotted") >> cloud2

# Дополнительная диаграмма с акцентом на работу одного Fog-узла
with Diagram("Цикл работы Fog-узла в системе",
             show=False,
             direction="TB"):

    # Центральный Fog-узел
    fog_node = Server("Fog-узел\n(динамическое состояние)")

    # Состояния вокруг узла
    standby_state = StateNode("① Ожидание\n(низкое энергопотребление)")
    receive_state = StateNode("② Получение\n(прием данных с края)")
    process_state = StateNode("③ Обработка\n(локальные вычисления)")
    send_state = StateNode("④ Передача\n(результаты наверх)")
    overload_state = StateNode("⑤ Перегрузка\n(балансировка нагрузки)")

    # Располагаем состояния по кругу
    standby_state - Edge(style="invis") - receive_state
    receive_state - Edge(style="invis") - process_state
    process_state - Edge(style="invis") - send_state
    send_state - Edge(style="invis") - overload_state
    overload_state - Edge(style="invis") - standby_state

    # Связь узла с состояниями
    fog_node >> Edge(color="blue", label="переходит в") >> standby_state
    fog_node >> Edge(color="blue", label="переходит в") >> receive_state
    fog_node >> Edge(color="blue", label="переходит в") >> process_state
    fog_node >> Edge(color="blue", label="переходит в") >> send_state
    fog_node >> Edge(color="blue", label="переходит в") >> overload_state

# Диаграмма оптимального распределения нагрузки
with Diagram("Оптимальное распределение нагрузки",
             show=False,
             direction="LR"):

    # Краевые устройства
    with Cluster("5 краевых устройств", graph_attr={"bgcolor": "lightblue"}):
        edges = [Mobile(f"Устр-во {i+1}") for i in range(5)]

    # Fog-узлы
    with Cluster("3 Fog-узла", graph_attr={"bgcolor": "lightgreen"}):
        fog_nodes = [Server(f"Fog {i+1}") for i in range(3)]

    # Облачные серверы
    with Cluster("2 облачных сервера", graph_attr={"bgcolor": "lightyellow"}):
        clouds = [Server(f"Облако {i+1}") for i in range(2)]
        storage = Storage("Хранилище")
        clouds[0] - clouds[1]
        clouds[0] >> storage
        clouds[1] >> storage

    # Оптимальные соединения (распределение 5->3)
    # Каждый Fog-узел обслуживает 1-2 устройства
    edges[0] >> fog_nodes[0]
    edges[1] >> fog_nodes[0]
    edges[2] >> fog_nodes[1]
    edges[3] >> fog_nodes[1]
    edges[4] >> fog_nodes[2]

    # Fog-узлы подключены к обоим облачным серверам
    for fog in fog_nodes:
        fog >> clouds[0]
        fog >> clouds[1]

    # Резервные соединения
    edges[0] >> Edge(style="dotted", color="gray") >> fog_nodes[2]  # резервное
    edges[4] >> Edge(style="dotted", color="gray") >> fog_nodes[0]  # резервное

print("=" * 70)
print("ДИАГРАММЫ СОЗДАНЫ УСПЕШНО!")
print("=" * 70)
print("\n📊 Оптимальная конфигурация системы:")
print("   └── 5 краевых устройств → 3 Fog-узла → 2 облачных сервера")
print("\n⚖️ Соотношение нагрузки:")
print("   ├── Каждый Fog-узел обрабатывает: 1-2 краевых устройства")
print("   ├── Общая нагрузка распределяется между 3 Fog-узлами")
print("   └── Облачные серверы дублируют функции для надежности")
print("\n🔄 Состояния Fog-узла:")
print("   1. Ожидание - готовность к работе")
print("   2. Получение - прием данных с края")
print("   3. Обработка - локальные вычисления")
print("   4. Передача - отправка результатов")
print("   5. Перегрузка - балансировка/очередь")
print("\n✅ Диаграммы сохранены в файлы:")
print("   - architecture.png")
print("   - state_diagram.png")
print("   - fog_cycle.png")
print("   - load_distribution.png")